// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TodoSchema is the predicate function for todoschema builders.
type TodoSchema func(*sql.Selector)
