// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_uow

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MockTransactionManager_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx
//   - fn
func (_e *MockTransactionManager_Expecter) RunInTx(ctx interface{}, fn interface{}) *MockTransactionManager_RunInTx_Call {
	return &MockTransactionManager_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *MockTransactionManager_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTransactionManager_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(ctx context.Context) error))
	})
	return _c
}

func (_c *MockTransactionManager_RunInTx_Call) Return(err error) *MockTransactionManager_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTransactionManager_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}
