// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectColumns holds the columns for the "project" table.
	ProjectColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
	}
	// ProjectTable holds the schema information for the "project" table.
	ProjectTable = &schema.Table{
		Name:       "project",
		Columns:    ProjectColumns,
		PrimaryKey: []*schema.Column{ProjectColumns[0]},
	}
	// TodoColumns holds the columns for the "todo" table.
	TodoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"NOT_STARTED", "IN_PROGRESS", "COMPLETED"}, Default: "NOT_STARTED"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// TodoTable holds the schema information for the "todo" table.
	TodoTable = &schema.Table{
		Name:       "todo",
		Columns:    TodoColumns,
		PrimaryKey: []*schema.Column{TodoColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "todoschema_deleted_at_created_at",
				Unique:  false,
				Columns: []*schema.Column{TodoColumns[7], TodoColumns[4]},
			},
			{
				Name:    "todoschema_deleted_at_updated_at",
				Unique:  false,
				Columns: []*schema.Column{TodoColumns[7], TodoColumns[5]},
			},
			{
				Name:    "todoschema_deleted_at_status",
				Unique:  false,
				Columns: []*schema.Column{TodoColumns[7], TodoColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectTable,
		TodoTable,
	}
)

func init() {
	ProjectTable.Annotation = &entsql.Annotation{
		Table:          "project",
		IncrementStart: func(i int) *int { return &i }(0),
	}
	TodoTable.Annotation = &entsql.Annotation{
		Table:          "todo",
		IncrementStart: func(i int) *int { return &i }(4294967296),
	}
}
