version = "2"

[run]
tests = true

[linters]
enable = [
	"errcheck",
	"errorlint",
	"govet",
	"ineffassign",
	"staticcheck",
	"unused",
]

[formatters]
enable = ["gofmt", "gofumpt", "gci", "golines"]

[issues]
max-same-issues = 0
max-issues-per-linter = 0
