// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/iktakahiro/oniongo/internal/infrastructure/sqlite/ent/todoschema"
	"github.com/iktakahiro/oniongo/internal/infrastructure/sqlite/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoschemaMixin := schema.TodoSchema{}.Mixin()
	todoschemaMixinFields0 := todoschemaMixin[0].Fields()
	_ = todoschemaMixinFields0
	todoschemaFields := schema.TodoSchema{}.Fields()
	_ = todoschemaFields
	// todoschemaDescCreatedAt is the schema descriptor for created_at field.
	todoschemaDescCreatedAt := todoschemaMixinFields0[1].Descriptor()
	// todoschema.DefaultCreatedAt holds the default value on creation for the created_at field.
	todoschema.DefaultCreatedAt = todoschemaDescCreatedAt.Default.(func() time.Time)
	// todoschemaDescUpdatedAt is the schema descriptor for updated_at field.
	todoschemaDescUpdatedAt := todoschemaMixinFields0[2].Descriptor()
	// todoschema.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todoschema.DefaultUpdatedAt = todoschemaDescUpdatedAt.Default.(func() time.Time)
	// todoschema.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todoschema.UpdateDefaultUpdatedAt = todoschemaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// todoschemaDescTitle is the schema descriptor for title field.
	todoschemaDescTitle := todoschemaFields[0].Descriptor()
	// todoschema.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todoschema.TitleValidator = todoschemaDescTitle.Validators[0].(func(string) error)
	// todoschemaDescID is the schema descriptor for id field.
	todoschemaDescID := todoschemaMixinFields0[0].Descriptor()
	// todoschema.DefaultID holds the default value on creation for the id field.
	todoschema.DefaultID = todoschemaDescID.Default.(func() uuid.UUID)
}
