// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TodoColumns holds the columns for the "todo" table.
	TodoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
	}
	// TodoTable holds the schema information for the "todo" table.
	TodoTable = &schema.Table{
		Name:       "todo",
		Columns:    TodoColumns,
		PrimaryKey: []*schema.Column{TodoColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TodoTable,
	}
)

func init() {
	TodoTable.Annotation = &entsql.Annotation{
		Table:          "todo",
		IncrementStart: func(i int) *int { return &i }(0),
	}
}
