// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/projectschema"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/todoschema"

	stdsql "database/sql"

	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ProjectSchema is the client for interacting with the ProjectSchema builders.
	ProjectSchema *ProjectSchemaClient
	// TodoSchema is the client for interacting with the TodoSchema builders.
	TodoSchema *TodoSchemaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ProjectSchema = NewProjectSchemaClient(c.config)
	c.TodoSchema = NewTodoSchemaClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		// schemaConfig contains alternative names for all tables.
		schemaConfig SchemaConfig
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entgen: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entgen: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ProjectSchema: NewProjectSchemaClient(cfg),
		TodoSchema:    NewTodoSchemaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ProjectSchema: NewProjectSchemaClient(cfg),
		TodoSchema:    NewTodoSchemaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ProjectSchema.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ProjectSchema.Use(hooks...)
	c.TodoSchema.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ProjectSchema.Intercept(interceptors...)
	c.TodoSchema.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ProjectSchemaMutation:
		return c.ProjectSchema.mutate(ctx, m)
	case *TodoSchemaMutation:
		return c.TodoSchema.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entgen: unknown mutation type %T", m)
	}
}

// ProjectSchemaClient is a client for the ProjectSchema schema.
type ProjectSchemaClient struct {
	config
}

// NewProjectSchemaClient returns a client for the ProjectSchema from the given config.
func NewProjectSchemaClient(c config) *ProjectSchemaClient {
	return &ProjectSchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projectschema.Hooks(f(g(h())))`.
func (c *ProjectSchemaClient) Use(hooks ...Hook) {
	c.hooks.ProjectSchema = append(c.hooks.ProjectSchema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projectschema.Intercept(f(g(h())))`.
func (c *ProjectSchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectSchema = append(c.inters.ProjectSchema, interceptors...)
}

// Create returns a builder for creating a ProjectSchema entity.
func (c *ProjectSchemaClient) Create() *ProjectSchemaCreate {
	mutation := newProjectSchemaMutation(c.config, OpCreate)
	return &ProjectSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectSchema entities.
func (c *ProjectSchemaClient) CreateBulk(builders ...*ProjectSchemaCreate) *ProjectSchemaCreateBulk {
	return &ProjectSchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectSchemaClient) MapCreateBulk(slice any, setFunc func(*ProjectSchemaCreate, int)) *ProjectSchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectSchemaCreateBulk{err: fmt.Errorf("calling to ProjectSchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectSchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectSchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectSchema.
func (c *ProjectSchemaClient) Update() *ProjectSchemaUpdate {
	mutation := newProjectSchemaMutation(c.config, OpUpdate)
	return &ProjectSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectSchemaClient) UpdateOne(ps *ProjectSchema) *ProjectSchemaUpdateOne {
	mutation := newProjectSchemaMutation(c.config, OpUpdateOne, withProjectSchema(ps))
	return &ProjectSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectSchemaClient) UpdateOneID(id uuid.UUID) *ProjectSchemaUpdateOne {
	mutation := newProjectSchemaMutation(c.config, OpUpdateOne, withProjectSchemaID(id))
	return &ProjectSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectSchema.
func (c *ProjectSchemaClient) Delete() *ProjectSchemaDelete {
	mutation := newProjectSchemaMutation(c.config, OpDelete)
	return &ProjectSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectSchemaClient) DeleteOne(ps *ProjectSchema) *ProjectSchemaDeleteOne {
	return c.DeleteOneID(ps.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectSchemaClient) DeleteOneID(id uuid.UUID) *ProjectSchemaDeleteOne {
	builder := c.Delete().Where(projectschema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectSchemaDeleteOne{builder}
}

// Query returns a query builder for ProjectSchema.
func (c *ProjectSchemaClient) Query() *ProjectSchemaQuery {
	return &ProjectSchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectSchema},
		inters: c.Interceptors(),
	}
}

// Get returns a ProjectSchema entity by its id.
func (c *ProjectSchemaClient) Get(ctx context.Context, id uuid.UUID) (*ProjectSchema, error) {
	return c.Query().Where(projectschema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectSchemaClient) GetX(ctx context.Context, id uuid.UUID) *ProjectSchema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProjectSchemaClient) Hooks() []Hook {
	return c.hooks.ProjectSchema
}

// Interceptors returns the client interceptors.
func (c *ProjectSchemaClient) Interceptors() []Interceptor {
	return c.inters.ProjectSchema
}

func (c *ProjectSchemaClient) mutate(ctx context.Context, m *ProjectSchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entgen: unknown ProjectSchema mutation op: %q", m.Op())
	}
}

// TodoSchemaClient is a client for the TodoSchema schema.
type TodoSchemaClient struct {
	config
}

// NewTodoSchemaClient returns a client for the TodoSchema from the given config.
func NewTodoSchemaClient(c config) *TodoSchemaClient {
	return &TodoSchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `todoschema.Hooks(f(g(h())))`.
func (c *TodoSchemaClient) Use(hooks ...Hook) {
	c.hooks.TodoSchema = append(c.hooks.TodoSchema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `todoschema.Intercept(f(g(h())))`.
func (c *TodoSchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.TodoSchema = append(c.inters.TodoSchema, interceptors...)
}

// Create returns a builder for creating a TodoSchema entity.
func (c *TodoSchemaClient) Create() *TodoSchemaCreate {
	mutation := newTodoSchemaMutation(c.config, OpCreate)
	return &TodoSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TodoSchema entities.
func (c *TodoSchemaClient) CreateBulk(builders ...*TodoSchemaCreate) *TodoSchemaCreateBulk {
	return &TodoSchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TodoSchemaClient) MapCreateBulk(slice any, setFunc func(*TodoSchemaCreate, int)) *TodoSchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TodoSchemaCreateBulk{err: fmt.Errorf("calling to TodoSchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TodoSchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TodoSchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TodoSchema.
func (c *TodoSchemaClient) Update() *TodoSchemaUpdate {
	mutation := newTodoSchemaMutation(c.config, OpUpdate)
	return &TodoSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TodoSchemaClient) UpdateOne(ts *TodoSchema) *TodoSchemaUpdateOne {
	mutation := newTodoSchemaMutation(c.config, OpUpdateOne, withTodoSchema(ts))
	return &TodoSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TodoSchemaClient) UpdateOneID(id uuid.UUID) *TodoSchemaUpdateOne {
	mutation := newTodoSchemaMutation(c.config, OpUpdateOne, withTodoSchemaID(id))
	return &TodoSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TodoSchema.
func (c *TodoSchemaClient) Delete() *TodoSchemaDelete {
	mutation := newTodoSchemaMutation(c.config, OpDelete)
	return &TodoSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TodoSchemaClient) DeleteOne(ts *TodoSchema) *TodoSchemaDeleteOne {
	return c.DeleteOneID(ts.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TodoSchemaClient) DeleteOneID(id uuid.UUID) *TodoSchemaDeleteOne {
	builder := c.Delete().Where(todoschema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TodoSchemaDeleteOne{builder}
}

// Query returns a query builder for TodoSchema.
func (c *TodoSchemaClient) Query() *TodoSchemaQuery {
	return &TodoSchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTodoSchema},
		inters: c.Interceptors(),
	}
}

// Get returns a TodoSchema entity by its id.
func (c *TodoSchemaClient) Get(ctx context.Context, id uuid.UUID) (*TodoSchema, error) {
	return c.Query().Where(todoschema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TodoSchemaClient) GetX(ctx context.Context, id uuid.UUID) *TodoSchema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TodoSchemaClient) Hooks() []Hook {
	return c.hooks.TodoSchema
}

// Interceptors returns the client interceptors.
func (c *TodoSchemaClient) Interceptors() []Interceptor {
	return c.inters.TodoSchema
}

func (c *TodoSchemaClient) mutate(ctx context.Context, m *TodoSchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TodoSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TodoSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TodoSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TodoSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entgen: unknown TodoSchema mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ProjectSchema, TodoSchema []ent.Hook
	}
	inters struct {
		ProjectSchema, TodoSchema []ent.Interceptor
	}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *config) {
		c.schemaConfig = schemaConfig
	}
}

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
