// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/todoschema"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProjectSchema = "ProjectSchema"
	TypeTodoSchema    = "TodoSchema"
)

// ProjectSchemaMutation represents an operation that mutates the ProjectSchema nodes in the graph.
type ProjectSchemaMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ProjectSchema, error)
	predicates    []predicate.ProjectSchema
}

var _ ent.Mutation = (*ProjectSchemaMutation)(nil)

// projectschemaOption allows management of the mutation configuration using functional options.
type projectschemaOption func(*ProjectSchemaMutation)

// newProjectSchemaMutation creates new mutation for the ProjectSchema entity.
func newProjectSchemaMutation(c config, op Op, opts ...projectschemaOption) *ProjectSchemaMutation {
	m := &ProjectSchemaMutation{
		config:        c,
		op:            op,
		typ:           TypeProjectSchema,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProjectSchemaID sets the ID field of the mutation.
func withProjectSchemaID(id uuid.UUID) projectschemaOption {
	return func(m *ProjectSchemaMutation) {
		var (
			err   error
			once  sync.Once
			value *ProjectSchema
		)
		m.oldValue = func(ctx context.Context) (*ProjectSchema, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ProjectSchema.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProjectSchema sets the old ProjectSchema of the mutation.
func withProjectSchema(node *ProjectSchema) projectschemaOption {
	return func(m *ProjectSchemaMutation) {
		m.oldValue = func(context.Context) (*ProjectSchema, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProjectSchemaMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProjectSchemaMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entgen: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ProjectSchema entities.
func (m *ProjectSchemaMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProjectSchemaMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProjectSchemaMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ProjectSchema.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// Where appends a list predicates to the ProjectSchemaMutation builder.
func (m *ProjectSchemaMutation) Where(ps ...predicate.ProjectSchema) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProjectSchemaMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProjectSchemaMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ProjectSchema, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProjectSchemaMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProjectSchemaMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ProjectSchema).
func (m *ProjectSchemaMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProjectSchemaMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProjectSchemaMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProjectSchemaMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown ProjectSchema field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectSchemaMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ProjectSchema field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProjectSchemaMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProjectSchemaMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectSchemaMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown ProjectSchema numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProjectSchemaMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProjectSchemaMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProjectSchemaMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ProjectSchema nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProjectSchemaMutation) ResetField(name string) error {
	return fmt.Errorf("unknown ProjectSchema field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProjectSchemaMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProjectSchemaMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProjectSchemaMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProjectSchemaMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProjectSchemaMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProjectSchemaMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProjectSchemaMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ProjectSchema unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProjectSchemaMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ProjectSchema edge %s", name)
}

// TodoSchemaMutation represents an operation that mutates the TodoSchema nodes in the graph.
type TodoSchemaMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	title         *string
	body          *string
	status        *todoschema.Status
	created_at    *time.Time
	updated_at    *time.Time
	completed_at  *time.Time
	deleted_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TodoSchema, error)
	predicates    []predicate.TodoSchema
}

var _ ent.Mutation = (*TodoSchemaMutation)(nil)

// todoschemaOption allows management of the mutation configuration using functional options.
type todoschemaOption func(*TodoSchemaMutation)

// newTodoSchemaMutation creates new mutation for the TodoSchema entity.
func newTodoSchemaMutation(c config, op Op, opts ...todoschemaOption) *TodoSchemaMutation {
	m := &TodoSchemaMutation{
		config:        c,
		op:            op,
		typ:           TypeTodoSchema,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTodoSchemaID sets the ID field of the mutation.
func withTodoSchemaID(id uuid.UUID) todoschemaOption {
	return func(m *TodoSchemaMutation) {
		var (
			err   error
			once  sync.Once
			value *TodoSchema
		)
		m.oldValue = func(ctx context.Context) (*TodoSchema, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TodoSchema.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTodoSchema sets the old TodoSchema of the mutation.
func withTodoSchema(node *TodoSchema) todoschemaOption {
	return func(m *TodoSchemaMutation) {
		m.oldValue = func(context.Context) (*TodoSchema, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TodoSchemaMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TodoSchemaMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entgen: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TodoSchema entities.
func (m *TodoSchemaMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TodoSchemaMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TodoSchemaMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TodoSchema.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *TodoSchemaMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *TodoSchemaMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *TodoSchemaMutation) ResetTitle() {
	m.title = nil
}

// SetBody sets the "body" field.
func (m *TodoSchemaMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *TodoSchemaMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldBody(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ClearBody clears the value of the "body" field.
func (m *TodoSchemaMutation) ClearBody() {
	m.body = nil
	m.clearedFields[todoschema.FieldBody] = struct{}{}
}

// BodyCleared returns if the "body" field was cleared in this mutation.
func (m *TodoSchemaMutation) BodyCleared() bool {
	_, ok := m.clearedFields[todoschema.FieldBody]
	return ok
}

// ResetBody resets all changes to the "body" field.
func (m *TodoSchemaMutation) ResetBody() {
	m.body = nil
	delete(m.clearedFields, todoschema.FieldBody)
}

// SetStatus sets the "status" field.
func (m *TodoSchemaMutation) SetStatus(t todoschema.Status) {
	m.status = &t
}

// Status returns the value of the "status" field in the mutation.
func (m *TodoSchemaMutation) Status() (r todoschema.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldStatus(ctx context.Context) (v todoschema.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *TodoSchemaMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *TodoSchemaMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TodoSchemaMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TodoSchemaMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TodoSchemaMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TodoSchemaMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TodoSchemaMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetCompletedAt sets the "completed_at" field.
func (m *TodoSchemaMutation) SetCompletedAt(t time.Time) {
	m.completed_at = &t
}

// CompletedAt returns the value of the "completed_at" field in the mutation.
func (m *TodoSchemaMutation) CompletedAt() (r time.Time, exists bool) {
	v := m.completed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCompletedAt returns the old "completed_at" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldCompletedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompletedAt: %w", err)
	}
	return oldValue.CompletedAt, nil
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (m *TodoSchemaMutation) ClearCompletedAt() {
	m.completed_at = nil
	m.clearedFields[todoschema.FieldCompletedAt] = struct{}{}
}

// CompletedAtCleared returns if the "completed_at" field was cleared in this mutation.
func (m *TodoSchemaMutation) CompletedAtCleared() bool {
	_, ok := m.clearedFields[todoschema.FieldCompletedAt]
	return ok
}

// ResetCompletedAt resets all changes to the "completed_at" field.
func (m *TodoSchemaMutation) ResetCompletedAt() {
	m.completed_at = nil
	delete(m.clearedFields, todoschema.FieldCompletedAt)
}

// SetDeletedAt sets the "deleted_at" field.
func (m *TodoSchemaMutation) SetDeletedAt(t time.Time) {
	m.deleted_at = &t
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *TodoSchemaMutation) DeletedAt() (r time.Time, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the TodoSchema entity.
// If the TodoSchema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoSchemaMutation) OldDeletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (m *TodoSchemaMutation) ClearDeletedAt() {
	m.deleted_at = nil
	m.clearedFields[todoschema.FieldDeletedAt] = struct{}{}
}

// DeletedAtCleared returns if the "deleted_at" field was cleared in this mutation.
func (m *TodoSchemaMutation) DeletedAtCleared() bool {
	_, ok := m.clearedFields[todoschema.FieldDeletedAt]
	return ok
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *TodoSchemaMutation) ResetDeletedAt() {
	m.deleted_at = nil
	delete(m.clearedFields, todoschema.FieldDeletedAt)
}

// Where appends a list predicates to the TodoSchemaMutation builder.
func (m *TodoSchemaMutation) Where(ps ...predicate.TodoSchema) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TodoSchemaMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TodoSchemaMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TodoSchema, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TodoSchemaMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TodoSchemaMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TodoSchema).
func (m *TodoSchemaMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TodoSchemaMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.title != nil {
		fields = append(fields, todoschema.FieldTitle)
	}
	if m.body != nil {
		fields = append(fields, todoschema.FieldBody)
	}
	if m.status != nil {
		fields = append(fields, todoschema.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, todoschema.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, todoschema.FieldUpdatedAt)
	}
	if m.completed_at != nil {
		fields = append(fields, todoschema.FieldCompletedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, todoschema.FieldDeletedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TodoSchemaMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case todoschema.FieldTitle:
		return m.Title()
	case todoschema.FieldBody:
		return m.Body()
	case todoschema.FieldStatus:
		return m.Status()
	case todoschema.FieldCreatedAt:
		return m.CreatedAt()
	case todoschema.FieldUpdatedAt:
		return m.UpdatedAt()
	case todoschema.FieldCompletedAt:
		return m.CompletedAt()
	case todoschema.FieldDeletedAt:
		return m.DeletedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TodoSchemaMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case todoschema.FieldTitle:
		return m.OldTitle(ctx)
	case todoschema.FieldBody:
		return m.OldBody(ctx)
	case todoschema.FieldStatus:
		return m.OldStatus(ctx)
	case todoschema.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case todoschema.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case todoschema.FieldCompletedAt:
		return m.OldCompletedAt(ctx)
	case todoschema.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	}
	return nil, fmt.Errorf("unknown TodoSchema field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TodoSchemaMutation) SetField(name string, value ent.Value) error {
	switch name {
	case todoschema.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case todoschema.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case todoschema.FieldStatus:
		v, ok := value.(todoschema.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case todoschema.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case todoschema.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case todoschema.FieldCompletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompletedAt(v)
		return nil
	case todoschema.FieldDeletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	}
	return fmt.Errorf("unknown TodoSchema field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TodoSchemaMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TodoSchemaMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TodoSchemaMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TodoSchema numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TodoSchemaMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(todoschema.FieldBody) {
		fields = append(fields, todoschema.FieldBody)
	}
	if m.FieldCleared(todoschema.FieldCompletedAt) {
		fields = append(fields, todoschema.FieldCompletedAt)
	}
	if m.FieldCleared(todoschema.FieldDeletedAt) {
		fields = append(fields, todoschema.FieldDeletedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TodoSchemaMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TodoSchemaMutation) ClearField(name string) error {
	switch name {
	case todoschema.FieldBody:
		m.ClearBody()
		return nil
	case todoschema.FieldCompletedAt:
		m.ClearCompletedAt()
		return nil
	case todoschema.FieldDeletedAt:
		m.ClearDeletedAt()
		return nil
	}
	return fmt.Errorf("unknown TodoSchema nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TodoSchemaMutation) ResetField(name string) error {
	switch name {
	case todoschema.FieldTitle:
		m.ResetTitle()
		return nil
	case todoschema.FieldBody:
		m.ResetBody()
		return nil
	case todoschema.FieldStatus:
		m.ResetStatus()
		return nil
	case todoschema.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case todoschema.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case todoschema.FieldCompletedAt:
		m.ResetCompletedAt()
		return nil
	case todoschema.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	}
	return fmt.Errorf("unknown TodoSchema field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TodoSchemaMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TodoSchemaMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TodoSchemaMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TodoSchemaMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TodoSchemaMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TodoSchemaMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TodoSchemaMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TodoSchema unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TodoSchemaMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TodoSchema edge %s", name)
}
