// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/projectschema"
)

// ProjectSchemaUpdate is the builder for updating ProjectSchema entities.
type ProjectSchemaUpdate struct {
	config
	hooks     []Hook
	mutation  *ProjectSchemaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProjectSchemaUpdate builder.
func (psu *ProjectSchemaUpdate) Where(ps ...predicate.ProjectSchema) *ProjectSchemaUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// Mutation returns the ProjectSchemaMutation object of the builder.
func (psu *ProjectSchemaUpdate) Mutation() *ProjectSchemaMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *ProjectSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *ProjectSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *ProjectSchemaUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *ProjectSchemaUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (psu *ProjectSchemaUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProjectSchemaUpdate {
	psu.modifiers = append(psu.modifiers, modifiers...)
	return psu
}

func (psu *ProjectSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectschema.Table, projectschema.Columns, sqlgraph.NewFieldSpec(projectschema.FieldID, field.TypeUUID))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Node.Schema = psu.schemaConfig.ProjectSchema
	ctx = internal.NewSchemaConfigContext(ctx, psu.schemaConfig)
	_spec.AddModifiers(psu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// ProjectSchemaUpdateOne is the builder for updating a single ProjectSchema entity.
type ProjectSchemaUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProjectSchemaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Mutation returns the ProjectSchemaMutation object of the builder.
func (psuo *ProjectSchemaUpdateOne) Mutation() *ProjectSchemaMutation {
	return psuo.mutation
}

// Where appends a list predicates to the ProjectSchemaUpdate builder.
func (psuo *ProjectSchemaUpdateOne) Where(ps ...predicate.ProjectSchema) *ProjectSchemaUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *ProjectSchemaUpdateOne) Select(field string, fields ...string) *ProjectSchemaUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated ProjectSchema entity.
func (psuo *ProjectSchemaUpdateOne) Save(ctx context.Context) (*ProjectSchema, error) {
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *ProjectSchemaUpdateOne) SaveX(ctx context.Context) *ProjectSchema {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *ProjectSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *ProjectSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (psuo *ProjectSchemaUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProjectSchemaUpdateOne {
	psuo.modifiers = append(psuo.modifiers, modifiers...)
	return psuo
}

func (psuo *ProjectSchemaUpdateOne) sqlSave(ctx context.Context) (_node *ProjectSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectschema.Table, projectschema.Columns, sqlgraph.NewFieldSpec(projectschema.FieldID, field.TypeUUID))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entgen: missing "ProjectSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectschema.FieldID)
		for _, f := range fields {
			if !projectschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
			}
			if f != projectschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.Node.Schema = psuo.schemaConfig.ProjectSchema
	ctx = internal.NewSchemaConfigContext(ctx, psuo.schemaConfig)
	_spec.AddModifiers(psuo.modifiers...)
	_node = &ProjectSchema{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
