// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/projectschema"
)

// ProjectSchemaDelete is the builder for deleting a ProjectSchema entity.
type ProjectSchemaDelete struct {
	config
	hooks    []Hook
	mutation *ProjectSchemaMutation
}

// Where appends a list predicates to the ProjectSchemaDelete builder.
func (psd *ProjectSchemaDelete) Where(ps ...predicate.ProjectSchema) *ProjectSchemaDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *ProjectSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *ProjectSchemaDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *ProjectSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectschema.Table, sqlgraph.NewFieldSpec(projectschema.FieldID, field.TypeUUID))
	_spec.Node.Schema = psd.schemaConfig.ProjectSchema
	ctx = internal.NewSchemaConfigContext(ctx, psd.schemaConfig)
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// ProjectSchemaDeleteOne is the builder for deleting a single ProjectSchema entity.
type ProjectSchemaDeleteOne struct {
	psd *ProjectSchemaDelete
}

// Where appends a list predicates to the ProjectSchemaDelete builder.
func (psdo *ProjectSchemaDeleteOne) Where(ps ...predicate.ProjectSchema) *ProjectSchemaDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *ProjectSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *ProjectSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
