// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/projectschema"
)

// ProjectSchemaQuery is the builder for querying ProjectSchema entities.
type ProjectSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []projectschema.OrderOption
	inters     []Interceptor
	predicates []predicate.ProjectSchema
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectSchemaQuery builder.
func (psq *ProjectSchemaQuery) Where(ps ...predicate.ProjectSchema) *ProjectSchemaQuery {
	psq.predicates = append(psq.predicates, ps...)
	return psq
}

// Limit the number of records to be returned by this query.
func (psq *ProjectSchemaQuery) Limit(limit int) *ProjectSchemaQuery {
	psq.ctx.Limit = &limit
	return psq
}

// Offset to start from.
func (psq *ProjectSchemaQuery) Offset(offset int) *ProjectSchemaQuery {
	psq.ctx.Offset = &offset
	return psq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (psq *ProjectSchemaQuery) Unique(unique bool) *ProjectSchemaQuery {
	psq.ctx.Unique = &unique
	return psq
}

// Order specifies how the records should be ordered.
func (psq *ProjectSchemaQuery) Order(o ...projectschema.OrderOption) *ProjectSchemaQuery {
	psq.order = append(psq.order, o...)
	return psq
}

// First returns the first ProjectSchema entity from the query.
// Returns a *NotFoundError when no ProjectSchema was found.
func (psq *ProjectSchemaQuery) First(ctx context.Context) (*ProjectSchema, error) {
	nodes, err := psq.Limit(1).All(setContextOp(ctx, psq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (psq *ProjectSchemaQuery) FirstX(ctx context.Context) *ProjectSchema {
	node, err := psq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectSchema ID from the query.
// Returns a *NotFoundError when no ProjectSchema ID was found.
func (psq *ProjectSchemaQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = psq.Limit(1).IDs(setContextOp(ctx, psq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (psq *ProjectSchemaQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := psq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectSchema entity is found.
// Returns a *NotFoundError when no ProjectSchema entities are found.
func (psq *ProjectSchemaQuery) Only(ctx context.Context) (*ProjectSchema, error) {
	nodes, err := psq.Limit(2).All(setContextOp(ctx, psq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectschema.Label}
	default:
		return nil, &NotSingularError{projectschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (psq *ProjectSchemaQuery) OnlyX(ctx context.Context) *ProjectSchema {
	node, err := psq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectSchema ID in the query.
// Returns a *NotSingularError when more than one ProjectSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (psq *ProjectSchemaQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = psq.Limit(2).IDs(setContextOp(ctx, psq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectschema.Label}
	default:
		err = &NotSingularError{projectschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (psq *ProjectSchemaQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := psq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectSchemas.
func (psq *ProjectSchemaQuery) All(ctx context.Context) ([]*ProjectSchema, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryAll)
	if err := psq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectSchema, *ProjectSchemaQuery]()
	return withInterceptors[[]*ProjectSchema](ctx, psq, qr, psq.inters)
}

// AllX is like All, but panics if an error occurs.
func (psq *ProjectSchemaQuery) AllX(ctx context.Context) []*ProjectSchema {
	nodes, err := psq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectSchema IDs.
func (psq *ProjectSchemaQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if psq.ctx.Unique == nil && psq.path != nil {
		psq.Unique(true)
	}
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryIDs)
	if err = psq.Select(projectschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (psq *ProjectSchemaQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := psq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (psq *ProjectSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryCount)
	if err := psq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, psq, querierCount[*ProjectSchemaQuery](), psq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (psq *ProjectSchemaQuery) CountX(ctx context.Context) int {
	count, err := psq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (psq *ProjectSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, psq.ctx, ent.OpQueryExist)
	switch _, err := psq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (psq *ProjectSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := psq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (psq *ProjectSchemaQuery) Clone() *ProjectSchemaQuery {
	if psq == nil {
		return nil
	}
	return &ProjectSchemaQuery{
		config:     psq.config,
		ctx:        psq.ctx.Clone(),
		order:      append([]projectschema.OrderOption{}, psq.order...),
		inters:     append([]Interceptor{}, psq.inters...),
		predicates: append([]predicate.ProjectSchema{}, psq.predicates...),
		// clone intermediate query.
		sql:       psq.sql.Clone(),
		path:      psq.path,
		modifiers: append([]func(*sql.Selector){}, psq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (psq *ProjectSchemaQuery) GroupBy(field string, fields ...string) *ProjectSchemaGroupBy {
	psq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectSchemaGroupBy{build: psq}
	grbuild.flds = &psq.ctx.Fields
	grbuild.label = projectschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (psq *ProjectSchemaQuery) Select(fields ...string) *ProjectSchemaSelect {
	psq.ctx.Fields = append(psq.ctx.Fields, fields...)
	sbuild := &ProjectSchemaSelect{ProjectSchemaQuery: psq}
	sbuild.label = projectschema.Label
	sbuild.flds, sbuild.scan = &psq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectSchemaSelect configured with the given aggregations.
func (psq *ProjectSchemaQuery) Aggregate(fns ...AggregateFunc) *ProjectSchemaSelect {
	return psq.Select().Aggregate(fns...)
}

func (psq *ProjectSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range psq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, psq); err != nil {
				return err
			}
		}
	}
	for _, f := range psq.ctx.Fields {
		if !projectschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if psq.path != nil {
		prev, err := psq.path(ctx)
		if err != nil {
			return err
		}
		psq.sql = prev
	}
	return nil
}

func (psq *ProjectSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectSchema, error) {
	var (
		nodes = []*ProjectSchema{}
		_spec = psq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectSchema{config: psq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = psq.schemaConfig.ProjectSchema
	ctx = internal.NewSchemaConfigContext(ctx, psq.schemaConfig)
	if len(psq.modifiers) > 0 {
		_spec.Modifiers = psq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, psq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (psq *ProjectSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := psq.querySpec()
	_spec.Node.Schema = psq.schemaConfig.ProjectSchema
	ctx = internal.NewSchemaConfigContext(ctx, psq.schemaConfig)
	if len(psq.modifiers) > 0 {
		_spec.Modifiers = psq.modifiers
	}
	_spec.Node.Columns = psq.ctx.Fields
	if len(psq.ctx.Fields) > 0 {
		_spec.Unique = psq.ctx.Unique != nil && *psq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, psq.driver, _spec)
}

func (psq *ProjectSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectschema.Table, projectschema.Columns, sqlgraph.NewFieldSpec(projectschema.FieldID, field.TypeUUID))
	_spec.From = psq.sql
	if unique := psq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if psq.path != nil {
		_spec.Unique = true
	}
	if fields := psq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectschema.FieldID)
		for i := range fields {
			if fields[i] != projectschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := psq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := psq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := psq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := psq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (psq *ProjectSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(psq.driver.Dialect())
	t1 := builder.Table(projectschema.Table)
	columns := psq.ctx.Fields
	if len(columns) == 0 {
		columns = projectschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if psq.sql != nil {
		selector = psq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if psq.ctx.Unique != nil && *psq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(psq.schemaConfig.ProjectSchema)
	ctx = internal.NewSchemaConfigContext(ctx, psq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range psq.modifiers {
		m(selector)
	}
	for _, p := range psq.predicates {
		p(selector)
	}
	for _, p := range psq.order {
		p(selector)
	}
	if offset := psq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := psq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (psq *ProjectSchemaQuery) ForUpdate(opts ...sql.LockOption) *ProjectSchemaQuery {
	if psq.driver.Dialect() == dialect.Postgres {
		psq.Unique(false)
	}
	psq.modifiers = append(psq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return psq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (psq *ProjectSchemaQuery) ForShare(opts ...sql.LockOption) *ProjectSchemaQuery {
	if psq.driver.Dialect() == dialect.Postgres {
		psq.Unique(false)
	}
	psq.modifiers = append(psq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return psq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (psq *ProjectSchemaQuery) Modify(modifiers ...func(s *sql.Selector)) *ProjectSchemaSelect {
	psq.modifiers = append(psq.modifiers, modifiers...)
	return psq.Select()
}

// ProjectSchemaGroupBy is the group-by builder for ProjectSchema entities.
type ProjectSchemaGroupBy struct {
	selector
	build *ProjectSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (psgb *ProjectSchemaGroupBy) Aggregate(fns ...AggregateFunc) *ProjectSchemaGroupBy {
	psgb.fns = append(psgb.fns, fns...)
	return psgb
}

// Scan applies the selector query and scans the result into the given value.
func (psgb *ProjectSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psgb.build.ctx, ent.OpQueryGroupBy)
	if err := psgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectSchemaQuery, *ProjectSchemaGroupBy](ctx, psgb.build, psgb, psgb.build.inters, v)
}

func (psgb *ProjectSchemaGroupBy) sqlScan(ctx context.Context, root *ProjectSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(psgb.fns))
	for _, fn := range psgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*psgb.flds)+len(psgb.fns))
		for _, f := range *psgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*psgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectSchemaSelect is the builder for selecting fields of ProjectSchema entities.
type ProjectSchemaSelect struct {
	*ProjectSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pss *ProjectSchemaSelect) Aggregate(fns ...AggregateFunc) *ProjectSchemaSelect {
	pss.fns = append(pss.fns, fns...)
	return pss
}

// Scan applies the selector query and scans the result into the given value.
func (pss *ProjectSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pss.ctx, ent.OpQuerySelect)
	if err := pss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectSchemaQuery, *ProjectSchemaSelect](ctx, pss.ProjectSchemaQuery, pss, pss.inters, v)
}

func (pss *ProjectSchemaSelect) sqlScan(ctx context.Context, root *ProjectSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pss.fns))
	for _, fn := range pss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pss *ProjectSchemaSelect) Modify(modifiers ...func(s *sql.Selector)) *ProjectSchemaSelect {
	pss.modifiers = append(pss.modifiers, modifiers...)
	return pss
}
