// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/todoschema"
)

// TodoSchemaDelete is the builder for deleting a TodoSchema entity.
type TodoSchemaDelete struct {
	config
	hooks    []Hook
	mutation *TodoSchemaMutation
}

// Where appends a list predicates to the TodoSchemaDelete builder.
func (tsd *TodoSchemaDelete) Where(ps ...predicate.TodoSchema) *TodoSchemaDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TodoSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TodoSchemaDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TodoSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todoschema.Table, sqlgraph.NewFieldSpec(todoschema.FieldID, field.TypeUUID))
	_spec.Node.Schema = tsd.schemaConfig.TodoSchema
	ctx = internal.NewSchemaConfigContext(ctx, tsd.schemaConfig)
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TodoSchemaDeleteOne is the builder for deleting a single TodoSchema entity.
type TodoSchemaDeleteOne struct {
	tsd *TodoSchemaDelete
}

// Where appends a list predicates to the TodoSchemaDelete builder.
func (tsdo *TodoSchemaDeleteOne) Where(ps ...predicate.TodoSchema) *TodoSchemaDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TodoSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todoschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TodoSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
