// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/internal"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/predicate"
	"github.com/iktakahiro/oniongo/internal/infrastructure/ent/entgen/todoschema"
)

// TodoSchemaQuery is the builder for querying TodoSchema entities.
type TodoSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []todoschema.OrderOption
	inters     []Interceptor
	predicates []predicate.TodoSchema
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TodoSchemaQuery builder.
func (tsq *TodoSchemaQuery) Where(ps ...predicate.TodoSchema) *TodoSchemaQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TodoSchemaQuery) Limit(limit int) *TodoSchemaQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TodoSchemaQuery) Offset(offset int) *TodoSchemaQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TodoSchemaQuery) Unique(unique bool) *TodoSchemaQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TodoSchemaQuery) Order(o ...todoschema.OrderOption) *TodoSchemaQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// First returns the first TodoSchema entity from the query.
// Returns a *NotFoundError when no TodoSchema was found.
func (tsq *TodoSchemaQuery) First(ctx context.Context) (*TodoSchema, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todoschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TodoSchemaQuery) FirstX(ctx context.Context) *TodoSchema {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TodoSchema ID from the query.
// Returns a *NotFoundError when no TodoSchema ID was found.
func (tsq *TodoSchemaQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todoschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TodoSchemaQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TodoSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TodoSchema entity is found.
// Returns a *NotFoundError when no TodoSchema entities are found.
func (tsq *TodoSchemaQuery) Only(ctx context.Context) (*TodoSchema, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todoschema.Label}
	default:
		return nil, &NotSingularError{todoschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TodoSchemaQuery) OnlyX(ctx context.Context) *TodoSchema {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TodoSchema ID in the query.
// Returns a *NotSingularError when more than one TodoSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TodoSchemaQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todoschema.Label}
	default:
		err = &NotSingularError{todoschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TodoSchemaQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TodoSchemas.
func (tsq *TodoSchemaQuery) All(ctx context.Context) ([]*TodoSchema, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryAll)
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TodoSchema, *TodoSchemaQuery]()
	return withInterceptors[[]*TodoSchema](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TodoSchemaQuery) AllX(ctx context.Context) []*TodoSchema {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TodoSchema IDs.
func (tsq *TodoSchemaQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryIDs)
	if err = tsq.Select(todoschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TodoSchemaQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TodoSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryCount)
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TodoSchemaQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TodoSchemaQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TodoSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryExist)
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TodoSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TodoSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TodoSchemaQuery) Clone() *TodoSchemaQuery {
	if tsq == nil {
		return nil
	}
	return &TodoSchemaQuery{
		config:     tsq.config,
		ctx:        tsq.ctx.Clone(),
		order:      append([]todoschema.OrderOption{}, tsq.order...),
		inters:     append([]Interceptor{}, tsq.inters...),
		predicates: append([]predicate.TodoSchema{}, tsq.predicates...),
		// clone intermediate query.
		sql:       tsq.sql.Clone(),
		path:      tsq.path,
		modifiers: append([]func(*sql.Selector){}, tsq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TodoSchema.Query().
//		GroupBy(todoschema.FieldTitle).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (tsq *TodoSchemaQuery) GroupBy(field string, fields ...string) *TodoSchemaGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TodoSchemaGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = todoschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.TodoSchema.Query().
//		Select(todoschema.FieldTitle).
//		Scan(ctx, &v)
func (tsq *TodoSchemaQuery) Select(fields ...string) *TodoSchemaSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TodoSchemaSelect{TodoSchemaQuery: tsq}
	sbuild.label = todoschema.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TodoSchemaSelect configured with the given aggregations.
func (tsq *TodoSchemaQuery) Aggregate(fns ...AggregateFunc) *TodoSchemaSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TodoSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !todoschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TodoSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TodoSchema, error) {
	var (
		nodes = []*TodoSchema{}
		_spec = tsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TodoSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TodoSchema{config: tsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = tsq.schemaConfig.TodoSchema
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tsq *TodoSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Schema = tsq.schemaConfig.TodoSchema
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TodoSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(todoschema.Table, todoschema.Columns, sqlgraph.NewFieldSpec(todoschema.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todoschema.FieldID)
		for i := range fields {
			if fields[i] != todoschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TodoSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(todoschema.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = todoschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(tsq.schemaConfig.TodoSchema)
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range tsq.modifiers {
		m(selector)
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tsq *TodoSchemaQuery) ForUpdate(opts ...sql.LockOption) *TodoSchemaQuery {
	if tsq.driver.Dialect() == dialect.Postgres {
		tsq.Unique(false)
	}
	tsq.modifiers = append(tsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tsq *TodoSchemaQuery) ForShare(opts ...sql.LockOption) *TodoSchemaQuery {
	if tsq.driver.Dialect() == dialect.Postgres {
		tsq.Unique(false)
	}
	tsq.modifiers = append(tsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tsq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tsq *TodoSchemaQuery) Modify(modifiers ...func(s *sql.Selector)) *TodoSchemaSelect {
	tsq.modifiers = append(tsq.modifiers, modifiers...)
	return tsq.Select()
}

// TodoSchemaGroupBy is the group-by builder for TodoSchema entities.
type TodoSchemaGroupBy struct {
	selector
	build *TodoSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TodoSchemaGroupBy) Aggregate(fns ...AggregateFunc) *TodoSchemaGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TodoSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, ent.OpQueryGroupBy)
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoSchemaQuery, *TodoSchemaGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TodoSchemaGroupBy) sqlScan(ctx context.Context, root *TodoSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TodoSchemaSelect is the builder for selecting fields of TodoSchema entities.
type TodoSchemaSelect struct {
	*TodoSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TodoSchemaSelect) Aggregate(fns ...AggregateFunc) *TodoSchemaSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TodoSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, ent.OpQuerySelect)
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoSchemaQuery, *TodoSchemaSelect](ctx, tss.TodoSchemaQuery, tss, tss.inters, v)
}

func (tss *TodoSchemaSelect) sqlScan(ctx context.Context, root *TodoSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tss *TodoSchemaSelect) Modify(modifiers ...func(s *sql.Selector)) *TodoSchemaSelect {
	tss.modifiers = append(tss.modifiers, modifiers...)
	return tss
}
